version: '3.8'

services:
  app:
    build:
      context: ./docker
    container_name: php-blog-app
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    extra_hosts:
      - host.docker.internal:host-gateway


  nginx:
    container_name: nginx-blog-app
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf/:/etc/nginx/nginx.conf

    ports:
      - "8085:80"
      - "4438:443"

    depends_on:
      - app
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres-blog-app
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8083:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
