
FROM nginx:alpine

# COPY nginx.conf /etc/nginx/conf.d/default.conf

# COPY nginx.conf /etc/nginx/nginx.old.conf

# COPY conf.d/default.conf /etc/nginx/conf.d/default.conf

# COPY sites/default.conf /etc/nginx/sites-available/default.conf

WORKDIR /var/www/html

CMD ["nginx"]

EXPOSE 80 443
